# NUMPY 3

**TOPIC**

In [1]:
import numpy as np

## np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [ ]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[43, 40, 20, 33],
       [80, 86, 12, 15],
       [41, 64, 55, 99],
       [18, 74, 84, 78],
       [44, 79, 80, 25],
       [32, 81, 71, 27]])

In [ ]:
np.sort(a)[::-1]

array([97, 90, 89, 86, 83, 67, 66, 65, 60, 56, 53, 47, 19,  9,  7])

In [ ]:
np.sort(b,axis=0)

array([[18, 40, 12, 15],
       [32, 64, 20, 25],
       [41, 74, 55, 27],
       [43, 79, 71, 33],
       [44, 81, 80, 78],
       [80, 86, 84, 99]])

In [ ]:
np.sort(b,axis=1)

array([[20, 33, 40, 43],
       [12, 15, 80, 86],
       [41, 55, 64, 99],
       [18, 74, 78, 84],
       [25, 44, 79, 80],
       [27, 32, 71, 81]])

## np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 86,  67,  65,  47,  53,   9,  83,  19,  66,  89,  90,  97,  56,
         7,  60, 200])

In [ ]:
b

array([[43, 40, 20, 33],
       [80, 86, 12, 15],
       [41, 64, 55, 99],
       [18, 74, 84, 78],
       [44, 79, 80, 25],
       [32, 81, 71, 27]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[4.30000000e+01, 4.00000000e+01, 2.00000000e+01, 3.30000000e+01,
        8.63097540e-01],
       [8.00000000e+01, 8.60000000e+01, 1.20000000e+01, 1.50000000e+01,
        2.65802228e-01],
       [4.10000000e+01, 6.40000000e+01, 5.50000000e+01, 9.90000000e+01,
        2.12688587e-02],
       [1.80000000e+01, 7.40000000e+01, 8.40000000e+01, 7.80000000e+01,
        3.77752327e-01],
       [4.40000000e+01, 7.90000000e+01, 8.00000000e+01, 2.50000000e+01,
        2.54112314e-01],
       [3.20000000e+01, 8.10000000e+01, 7.10000000e+01, 2.70000000e+01,
        4.59615638e-01]])

## np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [ ]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [ ]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [ ]:
a.shape

(15,)

In [ ]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [ ]:
np.expand_dims(a,axis=1).shape

(15, 1)

## np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  1,  2,  4,  6,  8,  9, 10, 11, 12, 14]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  0,  0, 47,  0,  9,  0, 19,  0,  0,  0,  0,  0,  7,  0])

In [ ]:
np.where(a%2 == 0,0,a)

array([ 0, 67, 65, 47, 53,  9, 83, 19,  0, 89,  0, 97,  0,  7,  0])

## np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [ ]:
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.argmax(a)

11

In [ ]:
b

array([[43, 40, 20, 33],
       [80, 86, 12, 15],
       [41, 64, 55, 99],
       [18, 74, 84, 78],
       [44, 79, 80, 25],
       [32, 81, 71, 27]])

In [ ]:
np.argmax(b,axis=0)

array([1, 1, 3, 2])

In [ ]:
np.argmax(b,axis=1)

array([0, 1, 3, 2, 2, 1])

In [ ]:
# np.argmin
np.argmin(a)

13

## np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.cumsum(a)

array([ 86, 153, 218, 265, 318, 327, 410, 429, 495, 584, 674, 771, 827,
       834, 894])

In [ ]:
b

array([[43, 40, 20, 33],
       [80, 86, 12, 15],
       [41, 64, 55, 99],
       [18, 74, 84, 78],
       [44, 79, 80, 25],
       [32, 81, 71, 27]])

In [ ]:
np.cumsum(b,axis=1)

array([[ 43,  83, 103, 136],
       [ 80, 166, 178, 193],
       [ 41, 105, 160, 259],
       [ 18,  92, 176, 254],
       [ 44, 123, 203, 228],
       [ 32, 113, 184, 211]])

In [ ]:
np.cumsum(b,axis=0)

array([[ 43,  40,  20,  33],
       [123, 126,  32,  48],
       [164, 190,  87, 147],
       [182, 264, 171, 225],
       [226, 343, 251, 250],
       [258, 424, 322, 277]])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  86,                 5762,               374530,
                   17602910,            932954230,           8396588070,
               696916809810,       13241419386390,      873933679501740,
          77780097475654860,  7000208772808937400, -3509279764786481992,
        6394517982762076224,  7868137731915430336, -7527082001522521856])

## np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [ ]:
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.percentile(a,50)

65.0

In [ ]:
np.median(a)

65.0

## np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.histogram(a,bins=[0,50,100])

(array([ 4, 11]), array([  0,  50, 100]))

## np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [ ]:
# code
a


array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([90, 60])

## np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.flip(a)

array([60,  7, 56, 97, 90, 89, 66, 19, 83,  9, 53, 47, 65, 67, 86])

In [ ]:
b

array([[43, 40, 20, 33],
       [80, 86, 12, 15],
       [41, 64, 55, 99],
       [18, 74, 84, 78],
       [44, 79, 80, 25],
       [32, 81, 71, 27]])

In [ ]:
np.flip(b,axis=1)

array([[33, 20, 40, 43],
       [15, 12, 86, 80],
       [99, 55, 64, 41],
       [78, 84, 74, 18],
       [25, 80, 79, 44],
       [27, 71, 81, 32]])

## np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [ ]:
# code
a

array([86, 67, 65, 47, 53,  9, 83, 19, 66, 89, 90, 97, 56,  7, 60])

In [ ]:
np.put(a,[0,1],[110,530])

## np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  65,  47,  53,   9,  83,  19,  66,  89,  90,  97,  56,
         7,  60])

In [ ]:
np.delete(a,[0,2,4])

array([530,  47,   9,  83,  19,  66,  89,  90,  97,  56,   7,  60])

## Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

## np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  65,  47,  53,   9,  83,  19,  66,  89,  90,  97,  56,
         7,  60])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 65, 47, 53, 25, 75, 25, 66, 75, 75, 75, 56, 25, 60])