# NUMPY 1

**TOPIC**

- What is numpy?
- Numpy Arrays Vs Python Sequences
- Creating Numpy Arrays
- Array Attributes
- Changing Datatype
- Array Operations
- Array Functions
- Indexing and Slicing
- Iterating
- Reshaping
- Stacking
- Splitting


## What is numpy?

- NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


- At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## Numpy Arrays Vs Python Sequences


- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## Creating Numpy Arrays

In [1]:
import numpy as np

In [ ]:
# 1D
a = np.array([1,2,3])

In [ ]:
print(a)

[1 2 3]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
# 2D
b = np.array(
    [[1,2,3],
     [4,5,6]]
  )

In [ ]:
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3D
c = np.array(
    [[
        [1,2],[3,4]
      ],
     [
         [3,4],[5,6]]
     ]
  )
print(c)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]


In [ ]:
c.dtype

dtype('int64')

In [ ]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.random.random((3,4))

array([[0.15989345, 0.30833941, 0.53549324, 0.91205188],
       [0.53695562, 0.58378084, 0.67411332, 0.75510617],
       [0.02855347, 0.35139875, 0.21972154, 0.43110056]])

In [ ]:
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
np.identity(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## Array Attributes

In [ ]:
a1 = np.arange(10, dtype=np.int32)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3.ndim

3

In [ ]:
a3.shape

(2, 2, 2)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
# Number of elements in the array.
a2.size

12

In [ ]:
# Length of one array element in bytes.
a2.itemsize

8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


## Changing Datatype

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a1 == 11

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [ ]:
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

## Array Functions

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
print(a1)

[[58. 62. 83.]
 [97. 99. 19.]
 [ 9. 44. 69.]]


In [ ]:
# max/min/sum/prod
# 0 -> col and 1 -> row
# Return the product of array elements over a given axis.
np.prod(a1,axis=0)

array([ 50634., 270072., 108813.])

In [ ]:
# mean/median/std/var
np.var(a1,axis=1)

array([ 120.22222222, 1387.55555556,  605.55555556])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.99287265, -0.7391807 ,  0.96836446],
       [ 0.37960774, -0.99920683,  0.14987721],
       [ 0.41211849,  0.01770193, -0.11478481]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(4,2)

np.dot(a2,a3)

array([[ 28,  34],
       [ 76,  98],
       [124, 162]])

In [ ]:
# log and exponents
np.exp(a1)

array([[1.54553894e+25, 8.43835667e+26, 1.11286375e+36],
       [1.33833472e+42, 9.88903032e+42, 1.78482301e+08],
       [8.10308393e+03, 1.28516001e+19, 9.25378173e+29]])

In [ ]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[67., 36., 75.],
       [21., 86., 13.]])

## Indexing and Slicing

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

## Iterating

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12).reshape(3,2,2)

In [ ]:
for i in a1:
  print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [ ]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [ ]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]
[[ 8  9]
 [10 11]]


In [ ]:
for i in np.nditer(a3):
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 

## Reshaping

In [ ]:
# Transpose
np.transpose(a2)
print(a2)
print(a2.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [ ]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Stacking

In [ ]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [ ]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [ ]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting

In [ ]:
# horizontal splitting
a4 = np.arange(12).reshape((3,4))
print(a4)
hs = np.hsplit(a4,2)
print(hs[0])
print(hs[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [ ]:
# vertical splitting
a5 = np.arange(16).reshape((4,4))
print(a5)
vs = np.vsplit(a5,4)
print(vs[0])
print(vs[1])
print(vs[2])
print(vs[3])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
